#!/usr/bin/env python3
"""
fetch_publications.py
---------------------
Scrapes your Google Scholar profile and writes publications.js
for use with your academic website.

Usage:
  pip install requests beautifulsoup4
  python fetch_publications.py

Edit SCHOLAR_URL below to point to your profile.
"""

import json
import sys
import time

try:
    import requests
    from bs4 import BeautifulSoup
except ImportError:
    print("Missing dependencies. Run:  pip install requests beautifulsoup4")
    sys.exit(1)

# ── Config ────────────────────────────────────────────────────
SCHOLAR_URL = "https://scholar.google.com/citations?user=WgGlcoYAAAAJ&sortby=pubdate"
# Replace YOUR_USER_ID with the `user=` value from your Scholar profile URL.
# Example: https://scholar.google.com/citations?user=fiaPSmgAAAAJ&sortby=pubdate

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    )
}
# ─────────────────────────────────────────────────────────────


def fetch_all_publications():
    pubs = []
    start = 0

    while True:
        url = f"{SCHOLAR_URL}&cstart={start}&pagesize=100"
        print(f"Fetching {url} ...")
        resp = requests.get(url, headers=HEADERS, timeout=15)

        if resp.status_code != 200:
            print(f"HTTP {resp.status_code} — Scholar may be blocking the request.")
            print("Try running again in a few minutes, or reduce request frequency.")
            break

        soup = BeautifulSoup(resp.text, "html.parser")
        rows = soup.select("tr.gsc_a_tr")

        if not rows:
            break

        for row in rows:
            title_el   = row.select_one(".gsc_a_at")
            authors_el = row.select_one(".gsc_a_at + .gs_gray")
            venue_el   = row.select_one(".gs_gray + .gs_gray")
            year_el    = row.select_one(".gsc_a_y span")
            cited_el   = row.select_one(".gsc_a_c a")
            link_el    = row.select_one(".gsc_a_at")

            title   = title_el.get_text(strip=True)   if title_el   else ""
            authors = authors_el.get_text(strip=True) if authors_el else ""
            venue   = venue_el.get_text(strip=True)   if venue_el   else ""
            year    = year_el.get_text(strip=True)    if year_el    else ""
            cited   = cited_el.get_text(strip=True)   if cited_el   else "0"
            href    = ("https://scholar.google.com" + link_el["data-href"]) if link_el and link_el.get("data-href") else ""

            pubs.append({
                "title":   title,
                "authors": authors,
                "venue":   venue,
                "year":    year,
                "cited":   cited,
                "url":     href,
            })

        # If fewer than 100 rows, we've reached the end
        if len(rows) < 100:
            break

        start += 100
        time.sleep(1.5)   # be polite

    return pubs


def write_js(pubs, path="publications.js"):
    js = (
        "// Auto-generated by fetch_publications.py — do not edit manually.\n"
        "// Re-run the script to update.\n"
        f"const PUBLICATIONS = {json.dumps(pubs, indent=2, ensure_ascii=False)};\n"
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(js)
    print(f"Wrote {len(pubs)} publications to {path}")


if __name__ == "__main__":
    pubs = fetch_all_publications()
    if pubs:
        write_js(pubs)
    else:
        print("No publications found. Check your SCHOLAR_URL and try again.")
