// Auto-generated by fetch_publications.py — do not edit manually.
// Re-run the script to update.
const PUBLICATIONS = [
  {
    "title": "Costus maasiorum: a new species of Neotropical Costaceae from western Ecuador",
    "authors": "D Skinner, E Valderrama, JL Clark, JB Landis, JJ Harden, CD Specht",
    "venue": "Blumea-Biodiversity, Evolution and Biogeography of Plants 70 (1), 116-124, 2026",
    "year": "2026",
    "cited": "",
    "url": ""
  },
  {
    "title": "AVITI library prep miniaturization and combining with Illumina data for phylogenomic and population genomic analyses",
    "authors": "JB Landis, E Hufnagel, JM Felton, JJ Harden, D Almeida, CD Specht",
    "venue": "BioRxiv, 2025.07. 30.667782, 2025",
    "year": "2025",
    "cited": "1",
    "url": ""
  },
  {
    "title": "The power to resolve relationships: identifying incongruence and precision of reduced representation and genome-wide data in phylogenomics and population genomics",
    "authors": "JM Felton, C Jelley, JJ Harden, J Scholten, L Graber, M Heeney, ...",
    "venue": "bioRxiv, 2025.07. 09.663802, 2025",
    "year": "2025",
    "cited": "",
    "url": ""
  },
  {
    "title": "Reference genome ofCalochortus tolmieiHook. & Arn. (Liliaceae), a cat's ear mariposa lily",
    "authors": "JB Landis, JJ Harden, E Eifler, GL Buttelman, AI Hernández, TJ Givnish, ...",
    "venue": "G3: Genes, Genomes, Genetics 15 (3), jkaf008, 2025",
    "year": "2025",
    "cited": "1",
    "url": ""
  }
];
